apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: flaskapp
  name: flaskapp
spec:
  containers:
  - image: zimomar/flaskapp
    name: flaskapp
    ports:
    - containerPort: 5000
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
