apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: flaskapp
  name: flaskapp
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    run: flaskapp
  type: NodePort
status:
  loadBalancer: {}
